
@baseUrl = http://localhost:3000

### Recados

GET {{baseUrl}}/recados

### Recados ID

GET {{baseUrl}}/recados/123

### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}

### ConceitosManualController

# @name ConceitosManualController

GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController

# @name ConceitosAutomaticoController

GET {{baseUrl}}/conceitos-automatico/
