
@baseUrl = http://localhost:3000

### Lista todos os recados

GET {{baseUrl}}/recados/
?limit=100
&offset=20
//&user=luiz

### Lista apenas um recado

GET {{baseUrl}}/recados/2

### Cria um recado

POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Te amo",
    "de": "Ariel",
    "para": "Juliana"
  }

### Atualiza um recado

PATCH  {{baseUrl}}/recados/4
Content-Type: application/json

{
    "lido": true
  }

### Apaga um recado

DELETE {{baseUrl}}/recados/3


